// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9iSd8ko3rHQdDOxQylW-jqUhThV8IO9I',
    appId: '1:524281591289:web:beda68ea882274e6847928',
    messagingSenderId: '524281591289',
    projectId: 'trip-planner-apps',
    authDomain: 'trip-planner-apps.firebaseapp.com',
    storageBucket: 'trip-planner-apps.appspot.com',
    measurementId: 'G-01JXFLF53S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6UtDosCLJtV7KzxQZavn6nGe7ivEjAKE',
    appId: '1:524281591289:android:291cce059112cd14847928',
    messagingSenderId: '524281591289',
    projectId: 'trip-planner-apps',
    storageBucket: 'trip-planner-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7IxDkrnrqsfJq9gnEgfBIvyZ-1kgfThg',
    appId: '1:524281591289:ios:9436e582a6b6b09e847928',
    messagingSenderId: '524281591289',
    projectId: 'trip-planner-apps',
    storageBucket: 'trip-planner-apps.appspot.com',
    iosBundleId: 'com.matdis.edu.matdisEdu',
  );
}
